### ISSUE TITLE
AttributeError: 'LHAPDFSet' object has no attribute 'GetMembers'

### ISSUE THREAD

**Issue by enocera** [N3PDF/pycompressor#42]
Hi @Radonirinaunimi , I'm trying to use pycompressor. While I run 
`$ pycomp runcards/runcard.yml`
I get the following error
`AttributeError: 'LHAPDFSet' object has no attribute 'GetMembers'`
I'm using LHAPDF v6.4.0.

**Comment by Radonirinaunimi** [comment]
Thanks @enocera for finding out this bug. I believe this was caused by some changes in `validphys`. https://github.com/N3PDF/pycompressor/pull/43 should fix this.

**Comment by enocera** [comment]
Thanks @Radonirinaunimi . Let me check if it works. The very quick reply is really appreciated!

**Comment by Radonirinaunimi** [comment]
Yes, please let me know. I had a bit of time during the Journal Club :-)

**Comment by enocera** [comment]
This is working fine now, thanks.

**Comment by Radonirinaunimi** [comment]
Perfect, thanks!
